stages:
  # Ensure Annif is installed
  install:
    cmd:
    - python3 -m venv venv
    - . venv/bin/activate && pip install -U pip wheel setuptools && pip install -r requirements.txt
    - cp requirements.txt venv-installed
    deps:
    - requirements.txt
    outs:
    - venv-installed:
        cache: false
  # Load KAUNO vocabulary
  loadvoc:
    cmd: venv/bin/annif load-vocab --force kauno corpora/kauno-skos-reduced.ttl
    deps:
    - venv-installed
    - corpora/kauno-skos-reduced.ttl
    outs:
    - data/vocabs/kauno
  # Train MLLM project
  train-mllm:
    cmd: venv/bin/annif train kauno-mllm-fi -j 8 -d 2000 corpora/kirjasampo/kirjasampo-kauno-train.tsv
    deps:
    - venv-installed
    - corpora/kirjasampo/kirjasampo-kauno-train.tsv
    - data/vocabs/kauno
    outs:
    - data/projects/kauno-mllm-fi
  # Train Omikuji projects (Parabel and Bonsai)
  train-omikuji:
    foreach:
      parabel:
        backend: parabel
      bonsai:
        backend: bonsai
    do:
      cmd: venv/bin/annif train kauno-${item.backend}-fi -j 8 corpora/kirjasampo/kirjasampo-kauno-train.tsv
      deps:
      - venv-installed
      - corpora/kirjasampo/kirjasampo-kauno-train.tsv
      - data/vocabs/kauno
      outs:
      - data/projects/kauno-${item.backend}-fi
  # Evaluate projects
  eval:
    foreach:
      - mllm
      - parabel
      - bonsai
      - ensemble
    do:
      cmd:
      - venv/bin/annif eval kauno-${item}-fi -j 8 -m F1@5 -m NDCG --metrics-file reports/kauno-${item}-fi.json corpora/kirjasampo/kirjasampo-kauno-test.tsv
      deps:
      - venv-installed
      - corpora/kirjasampo/kirjasampo-kauno-test.tsv
      - data/projects/kauno-${item}-fi
      metrics:
      - reports/kauno-${item}-fi.json:
          cache: false
