# KAUNO Finnish

[kauno-mllm-fi]
language="fi"
backend="mllm"
analyzer="voikko(fi)"
vocab="kauno"

[kauno-parabel-fi]
language="fi"
backend="omikuji"
analyzer="voikko(fi)"
vocab="kauno"
transform="limit(5000)"

[kauno-bonsai-fi]
language="fi"
backend="omikuji"
analyzer="voikko(fi)"
vocab="kauno"
cluster_balanced=false
cluster_k=100
max_depth=3
min_df=2
ngram=2
transform="limit(5000)"

[kauno-ensemble-fi]
language="fi"
backend="omikuji"
sources="kauno-mllm-fi,kauno-parabel-fi,kauno-bonsai-fi"
vocab="kauno"
