# KAUNO Finnish

[kauno-mllm-fi]
name="KAUNO MLLM Finnish"
language="fi"
backend="mllm"
analyzer="voikko(fi)"
vocab="kauno"

[kauno-ks-bonsai-fi]
name="KAUNO KS Omikuji Bonsai Finnish"
language="fi"
backend="omikuji"
analyzer="voikko(fi)"
vocab="kauno"
cluster_balanced=false
cluster_k=100
max_depth=3
min_df=2
ngram=2
transform="limit(5000)"

[kauno-finna-bonsai-fi]
name="KAUNO Finna Omikuji Bonsai Finnish"
language="fi"
backend="omikuji"
analyzer="voikko(fi)"
vocab="kauno"
cluster_balanced=false
cluster_k=100
max_depth=3
min_df=2
ngram=2
transform="limit(5000)"

[kauno-ensemble-fi]
name="KAUNO Ensemble Finnish"
language="fi"
backend="nn_ensemble"
#sources="kauno-mllm-fi,kauno-ks-bonsai-fi,kauno-finna-bonsai-fi"
sources="kauno-mllm-fi:0.1293,kauno-ks-bonsai-fi:0.5518,kauno-finna-bonsai-fi:0.3189"
vocab="kauno"
